version: "3.9"

networks:
  todoapi_network:
    driver: bridge

volumes:
  todoapi_data:
    driver: local

services:
  postgres-service:
    container_name: postgres
    image: postgres
    working_dir: /usr/src/app
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - todoapi_data:/var/opt/pgsql
    networks:
      - todoapi_network

  api:
    build: .
    container_name: todoapi
    restart: unless-stopped
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      - DATABASE=Host=postgres-service;Database=postgres;Username=postgres;Password=password
    depends_on:
      - postgres-service
    networks:
      - todoapi_network
