FROM mcr.microsoft.com/dotnet/sdk:5.0
WORKDIR /app

LABEL author="Helton Reis"

RUN dotnet tool install --global dotnet-ef
ENV PATH /root/.dotnet/tools:$PATH


COPY . .

RUN cd Core && dotnet restore; cd .. \
	&& cd Infrastructure && dotnet restore; cd .. \
	&& cd API && dotnet restore; npm install; cd ..

EXPOSE 5000
EXPOSE 5001

ENTRYPOINT ["./entrypoint.prod.sh"]